### ISSUE TITLE
Bug on shutdown

### ISSUE THREAD

**Issue by niget2002** [niget2002/Octoprint-I2cTempControl#3]
After print is finished, following bug occurs.

`2023-05-01 06:29:01,634 - octoprint.printer.standard - ERROR - Exception while sending print progress to plugin i2ctempcontrol
Traceback (most recent call last):
  File "/home/dwalling/oprint/lib/python3.9/site-packages/octoprint/printer/standard.py", line 327, in call_plugins
    plugin.on_print_progress(storage, filename, progress)
  File "/home/dwalling/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/dwalling/oprint/lib/python3.9/site-packages/octoprint_i2ctempcontrol/__init__.py", line 266, in on_print_progress
    self.shutdownTimer = octoprint.util.RepeatedTimer(600.0, self.jobIsDone())
  File "/home/dwalling/oprint/lib/python3.9/site-packages/octoprint_i2ctempcontrol/__init__.py", line 270, in jobIsDone
    self.shutdownTimer.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'`

**Comment by niget2002** [comment]
This has been resolved. Issue was with the way the shutdown function was called.
